FROM apache/airflow:2.7.1
USER root
# Install any system dependencies required for your plugin here
# For example, git, if you need to clone a repository
RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    && apt-get clean && rm -rf /var/lib/apt/lists/*
USER airflow
RUN pip install openpyxl==3.1.4