name: Build and Publish Docker Image on Commit

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Publish Docker Image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build and push Docker image
      uses: Ferlab-Ste-Justine/action-push-image@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        context: ./cypress
        image: your-dockerhub-username/cypress-image
        tag_format: "latest"
