name: Build and Publish Docker Image on Commit

on:
  push:
    branches:
      - main
    paths:
      - Dockerfile.cypress-included-custom

jobs:
  publish_cypress_custom_image:
    name: Publish Cypress Custom Image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build the cypress image
        run: docker build -t ferlabcrsj/cypress-included-custom:latest -f ./custom-docker-images/Dockerfile.cypress-included-custom ./custom-docker-images
      - name: Push the image on the docker registry
        uses: Ferlab-Ste-Justine/action-push-image@v2
        with:
          username: ${{ secrets.FERLAB_DOCKER_HUB_USER }}
          password: ${{ secrets.FERLAB_DOCKER_HUB_TOKEN }}
          image: ferlabcrsj/cypress-included-custom
          tag_format: "latest"
          location: './custom-docker-images'
          dockerfile: 'Dockerfile.cypress-included-custom'