name: Build and Publish Airflow Custom Image on Commit

on:
  push:
    branches:
      - main
    paths:
      - Dockerfile.airflow-custom

jobs:
  publish_airflow_custom_image:
    name: Publish Airflow Custom Image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Push the Airflow custom image on the docker registry
        uses: Ferlab-Ste-Justine/action-push-image@v2
        with:
          username: ${{ secrets.FERLAB_DOCKER_HUB_USER }}
          password: ${{ secrets.FERLAB_DOCKER_HUB_TOKEN }}
          image: ferlabcrsj/airflow-custom
          tag_format: "latest"
          dockerfile: "Dockerfile.airflow-custom"