name: Build and Publish Docker Image on Commit

on:
  push:
    branches:
      - main

jobs:
  publish_cypress_custom_image:
    name: Publish Cypress Custom Image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Push the image on the docker registry
        uses: Ferlab-Ste-Justine/action-push-image@v2
        with:
          username: ${{ secrets.FERLAB_DOCKER_HUB_USER }}
          password: ${{ secrets.FERLAB_DOCKER_HUB_TOKEN }}
          image: ferlabcrsj/cypress-included-custom
          tag_format: "latest"

  publish_airflow_custom_image:
      name: Publish Airflow Custom Image
      runs-on: ubuntu-20.04
      steps:
        - uses: actions/checkout@v2
        - name: Build the Airflow custom image
          run: docker build -t ferlabcrsj/airflow-custom:latest -f Dockerfile.airflow-custom .
        - name: Push the Airflow custom image on the docker registry
          uses: Ferlab-Ste-Justine/action-push-image@v2
          with:
            username: ${{ secrets.FERLAB_DOCKER_HUB_USER }}
            password: ${{ secrets.FERLAB_DOCKER_HUB_TOKEN }}
            image: ferlabcrsj/airflow-custom
            tag_format: "latest"